name: Build and Deploy Jekyll
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.x
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
